on:
  push:
    branches:
      - master

name: Deploy to Amazon S3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        npm i
        npm run lint
        npm run build
        ls

    - name: AWS S3 Sync Action
      uses: awact/s3-action@0.1.1
      with:
        AWS_REGION: "eu-central-1"
        SOURCE_DIR: www
